// Code generated by MockGen. DO NOT EDIT.
// Source: public_handler.go

// Package mock_handler is a generated GoMock package.
package mock_handler

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/vavelour/chat/internal/domain/entities"
)

// MockPublicService is a mock of PublicService interface.
type MockPublicService struct {
	ctrl     *gomock.Controller
	recorder *MockPublicServiceMockRecorder
}

// MockPublicServiceMockRecorder is the mock recorder for MockPublicService.
type MockPublicServiceMockRecorder struct {
	mock *MockPublicService
}

// NewMockPublicService creates a new mock instance.
func NewMockPublicService(ctrl *gomock.Controller) *MockPublicService {
	mock := &MockPublicService{ctrl: ctrl}
	mock.recorder = &MockPublicServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublicService) EXPECT() *MockPublicServiceMockRecorder {
	return m.recorder
}

// GetPublicMessages mocks base method.
func (m *MockPublicService) GetPublicMessages(limit, offset int) ([]entities.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicMessages", limit, offset)
	ret0, _ := ret[0].([]entities.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicMessages indicates an expected call of GetPublicMessages.
func (mr *MockPublicServiceMockRecorder) GetPublicMessages(limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicMessages", reflect.TypeOf((*MockPublicService)(nil).GetPublicMessages), limit, offset)
}

// SendPublicMessage mocks base method.
func (m_2 *MockPublicService) SendPublicMessage(m entities.Message) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendPublicMessage", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendPublicMessage indicates an expected call of SendPublicMessage.
func (mr *MockPublicServiceMockRecorder) SendPublicMessage(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendPublicMessage", reflect.TypeOf((*MockPublicService)(nil).SendPublicMessage), m)
}
